php:
- 7.0
- 7.1
- 7.2

services:
- mysql

before_script:
- cp .env.travis .env
- mysql -e 'create database laravel;'
- composer self-update
- composer update
- php artisan key:generate
- php artisan migrate --seed

script:
    - vendor/bin/phpunit

notifications:
email:
    recipients:
        - youremail@x.com
    on_success: always
    on_failure: always